// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5IcuAXFe-JgpNAIAi95Kd72GgZjrf_E',
    appId: '1:753290808180:web:6e8d1715b14c84dad5ba21',
    messagingSenderId: '753290808180',
    projectId: 'wenh-c9176',
    authDomain: 'wenh-c9176.firebaseapp.com',
    storageBucket: 'wenh-c9176.firebasestorage.app',
    measurementId: 'G-QW1BMBN3XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAivnx88y1RnbqXjaB_ElYM9JIA8hShIec',
    appId: '1:753290808180:android:fdcf4a30b2fbe202d5ba21',
    messagingSenderId: '753290808180',
    projectId: 'wenh-c9176',
    storageBucket: 'wenh-c9176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLSalpWOm_QdYbMihC-KUh1odm1PgpQU',
    appId: '1:753290808180:ios:e9568bb74e1c9271d5ba21',
    messagingSenderId: '753290808180',
    projectId: 'wenh-c9176',
    storageBucket: 'wenh-c9176.firebasestorage.app',
    iosClientId: '753290808180-o0jgqa3hphc1opo9qm72vvsmshmls1lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wenh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLSalpWOm_QdYbMihC-KUh1odm1PgpQU',
    appId: '1:753290808180:ios:e9568bb74e1c9271d5ba21',
    messagingSenderId: '753290808180',
    projectId: 'wenh-c9176',
    storageBucket: 'wenh-c9176.firebasestorage.app',
    iosClientId: '753290808180-o0jgqa3hphc1opo9qm72vvsmshmls1lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wenh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5IcuAXFe-JgpNAIAi95Kd72GgZjrf_E',
    appId: '1:753290808180:web:68f59c8c8b23dc98d5ba21',
    messagingSenderId: '753290808180',
    projectId: 'wenh-c9176',
    authDomain: 'wenh-c9176.firebaseapp.com',
    storageBucket: 'wenh-c9176.firebasestorage.app',
    measurementId: 'G-EFDSR0TN4P',
  );
}
